-- ============================================================
-- Deal diligence: documents, chunks, embeddings, finding reviews
--
-- Adds the document-corpus + RAG + approval surface that turns the
-- deal portal into a credible diligence platform alongside the existing
-- process-mapping flow.
--
-- New tables:
--   deal_documents        - uploaded files per deal (PDF/DOCX/XLSX/PPTX/...)
--   deal_document_chunks  - parsed text chunks with optional embeddings (pgvector)
--   deal_finding_reviews  - per-finding approval state for AI analysis output
--
-- New columns on deal_analyses: none. Findings live inside result JSONB and
-- carry their own evidence[]/confidence/impact fields. Approval state is in
-- the separate deal_finding_reviews table keyed by (analysis_id, finding_key)
-- to survive analysis re-runs and shape changes.
--
-- Embeddings use Voyage AI's voyage-3-large model (1024 dims). VOYAGE_API_KEY
-- env var required; embeddings are generated by the Inngest worker so the
-- table works without it (semantic search degrades to keyword FTS).
-- ============================================================

-- ---------- Required extensions ----------
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ---------- deal_documents ----------
CREATE TABLE IF NOT EXISTS public.deal_documents (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  deal_id           uuid        NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,

  filename          text        NOT NULL,
  mime_type         text,
  byte_size         bigint,

  -- Where the file lives in Supabase Storage. Bucket: 'deal-documents'.
  storage_path      text,

  -- Lifecycle of the chunking + embedding pipeline.
  -- pending   - row inserted, file uploaded, worker not started
  -- parsing   - worker is extracting text
  -- embedding - text extracted, embeddings being generated
  -- ready     - chunks + embeddings written, available for search
  -- failed    - terminal failure; see processing_error
  status            text        NOT NULL DEFAULT 'pending'
                      CHECK (status IN ('pending','parsing','embedding','ready','failed')),
  processing_error  text,

  -- Optional metadata captured at upload time. Free-form so the diligence
  -- UI can surface custom labels without a schema change.
  label             text,                  -- e.g. "CIM", "Q3 financials"
  source_party      text,                  -- which side provided it ('acquirer','target','seller','self',...)
  tags              text[]      DEFAULT '{}',

  page_count        integer,               -- populated post-parse where applicable

  uploaded_by_email text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deal_documents_deal    ON public.deal_documents (deal_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_deal_documents_status  ON public.deal_documents (status);
CREATE INDEX IF NOT EXISTS idx_deal_documents_party   ON public.deal_documents (deal_id, source_party);

COMMENT ON TABLE public.deal_documents IS
  'Uploaded source documents for a deal (CIM, financials, contracts...). Chunks + embeddings live in deal_document_chunks.';

-- ---------- deal_document_chunks ----------
-- Chunks are produced by the Inngest worker. Embedding column is nullable so
-- the row exists for keyword FTS even before embeddings finish.
CREATE TABLE IF NOT EXISTS public.deal_document_chunks (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id   uuid        NOT NULL REFERENCES public.deal_documents(id) ON DELETE CASCADE,
  deal_id       uuid        NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,

  chunk_index   integer     NOT NULL,    -- 0-based ordinal within the document

  -- Locator inside the source. At least one is populated where applicable:
  --   page         - PDFs / scanned docs
  --   slide        - PPTX
  --   sheet/range  - XLSX
  --   section      - DOCX heading path
  page_number   integer,
  slide_number  integer,
  sheet_name    text,
  cell_range    text,
  section_path  text,

  content       text        NOT NULL,
  token_count   integer,

  embedding     vector(1024),             -- voyage-3-large; nullable until embedded
  embedded_at   timestamptz,

  -- Pre-computed FTS document for keyword search (covers the keyword half of
  -- the hybrid retrieval; the embedding covers the semantic half).
  content_fts   tsvector
                  GENERATED ALWAYS AS (to_tsvector('english', coalesce(content, ''))) STORED,

  created_at    timestamptz NOT NULL DEFAULT now(),

  UNIQUE (document_id, chunk_index)
);

CREATE INDEX IF NOT EXISTS idx_chunks_deal      ON public.deal_document_chunks (deal_id);
CREATE INDEX IF NOT EXISTS idx_chunks_document  ON public.deal_document_chunks (document_id, chunk_index);
CREATE INDEX IF NOT EXISTS idx_chunks_fts       ON public.deal_document_chunks USING GIN (content_fts);
CREATE INDEX IF NOT EXISTS idx_chunks_trgm      ON public.deal_document_chunks USING GIN (content gin_trgm_ops);

-- HNSW index for cosine semantic search on the embedding vector.
-- m=16, ef_construction=64 are pgvector defaults; tune later under load.
CREATE INDEX IF NOT EXISTS idx_chunks_embedding
  ON public.deal_document_chunks
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);

COMMENT ON TABLE public.deal_document_chunks IS
  'Chunked text from deal_documents with optional embeddings + FTS. Drives /api/deals/[id]/search.';

-- ---------- deal_finding_reviews ----------
-- One row per (analysis, finding) reviewed by a human. Findings sit inside
-- deal_analyses.result JSONB; we key by a stable hash so the row survives
-- result re-shapes. Pending findings are hidden from the deal report unless
-- the viewer is an editor.
CREATE TABLE IF NOT EXISTS public.deal_finding_reviews (
  id            uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  analysis_id   uuid        NOT NULL REFERENCES public.deal_analyses(id) ON DELETE CASCADE,
  deal_id       uuid        NOT NULL REFERENCES public.deals(id) ON DELETE CASCADE,

  -- Stable identifier for a finding within an analysis result. Computed by the
  -- API from the finding's category + title (sha1 first 12 chars). The same
  -- finding produced by a re-run keeps the same key, so reviewer decisions
  -- carry forward.
  finding_key   text        NOT NULL,

  status        text        NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected','needs_revision')),
  reviewer_note text,

  -- Optional human-edited copy. Renderer prefers these fields when present;
  -- otherwise the original AI-generated values from result JSONB are shown.
  edited_title  text,
  edited_body   text,

  decided_by_email text,
  decided_at       timestamptz,

  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now(),

  UNIQUE (analysis_id, finding_key)
);

CREATE INDEX IF NOT EXISTS idx_finding_reviews_analysis ON public.deal_finding_reviews (analysis_id);
CREATE INDEX IF NOT EXISTS idx_finding_reviews_deal     ON public.deal_finding_reviews (deal_id, status);

COMMENT ON TABLE public.deal_finding_reviews IS
  'Per-finding approval state. Pending/rejected findings are hidden from the rendered deal report unless the viewer is an editor.';

-- ---------- updated_at triggers ----------
CREATE OR REPLACE FUNCTION public.set_updated_at_now()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN NEW.updated_at = now(); RETURN NEW; END $$;

DROP TRIGGER IF EXISTS deal_documents_updated_at ON public.deal_documents;
CREATE TRIGGER deal_documents_updated_at
  BEFORE UPDATE ON public.deal_documents
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_now();

DROP TRIGGER IF EXISTS deal_finding_reviews_updated_at ON public.deal_finding_reviews;
CREATE TRIGGER deal_finding_reviews_updated_at
  BEFORE UPDATE ON public.deal_finding_reviews
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at_now();

-- ---------- RLS ----------
-- Mirrors the deals RLS model: owner OR collaborator (by email) can read/write.
-- Anonymous participants do not get document or finding access — those flow
-- through the deal page only for editors.

ALTER TABLE public.deal_documents       ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deal_document_chunks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.deal_finding_reviews ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS deal_documents_editor ON public.deal_documents;
CREATE POLICY deal_documents_editor
  ON public.deal_documents
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.deals d
       WHERE d.id = deal_documents.deal_id
         AND (
           lower(d.owner_email) = lower(auth.jwt() ->> 'email')
           OR (auth.jwt() ->> 'email') = ANY (
             SELECT lower(e) FROM unnest(coalesce(d.collaborator_emails, ARRAY[]::text[])) AS e
           )
         )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.deals d
       WHERE d.id = deal_documents.deal_id
         AND (
           lower(d.owner_email) = lower(auth.jwt() ->> 'email')
           OR (auth.jwt() ->> 'email') = ANY (
             SELECT lower(e) FROM unnest(coalesce(d.collaborator_emails, ARRAY[]::text[])) AS e
           )
         )
    )
  );

DROP POLICY IF EXISTS deal_chunks_editor ON public.deal_document_chunks;
CREATE POLICY deal_chunks_editor
  ON public.deal_document_chunks
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.deals d
       WHERE d.id = deal_document_chunks.deal_id
         AND (
           lower(d.owner_email) = lower(auth.jwt() ->> 'email')
           OR (auth.jwt() ->> 'email') = ANY (
             SELECT lower(e) FROM unnest(coalesce(d.collaborator_emails, ARRAY[]::text[])) AS e
           )
         )
    )
  );

DROP POLICY IF EXISTS deal_finding_reviews_editor ON public.deal_finding_reviews;
CREATE POLICY deal_finding_reviews_editor
  ON public.deal_finding_reviews
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.deals d
       WHERE d.id = deal_finding_reviews.deal_id
         AND (
           lower(d.owner_email) = lower(auth.jwt() ->> 'email')
           OR (auth.jwt() ->> 'email') = ANY (
             SELECT lower(e) FROM unnest(coalesce(d.collaborator_emails, ARRAY[]::text[])) AS e
           )
         )
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.deals d
       WHERE d.id = deal_finding_reviews.deal_id
         AND (
           lower(d.owner_email) = lower(auth.jwt() ->> 'email')
           OR (auth.jwt() ->> 'email') = ANY (
             SELECT lower(e) FROM unnest(coalesce(d.collaborator_emails, ARRAY[]::text[])) AS e
           )
         )
    )
  );

-- ---------- Hybrid search RPC ----------
-- Combines cosine similarity + FTS rank with reciprocal rank fusion (RRF).
-- Callers pass deal_id (RLS-bounded), the query embedding, and the raw query
-- text for keyword scoring. Returns chunks ordered by fused score.
CREATE OR REPLACE FUNCTION public.search_deal_chunks(
  p_deal_id      uuid,
  p_query_text   text,
  p_query_vector vector(1024) DEFAULT NULL,
  p_limit        integer      DEFAULT 12,
  p_party        text         DEFAULT NULL
)
RETURNS TABLE (
  chunk_id       uuid,
  document_id    uuid,
  filename       text,
  page_number    integer,
  slide_number   integer,
  sheet_name     text,
  cell_range     text,
  section_path   text,
  content        text,
  semantic_score real,
  keyword_score  real,
  fused_score    real
)
LANGUAGE sql STABLE AS $$
  WITH semantic AS (
    SELECT c.id,
           CASE
             WHEN p_query_vector IS NOT NULL AND c.embedding IS NOT NULL
               THEN 1 - (c.embedding <=> p_query_vector)
             ELSE 0
           END                                                  AS score,
           ROW_NUMBER() OVER (
             ORDER BY CASE
               WHEN p_query_vector IS NOT NULL AND c.embedding IS NOT NULL
                 THEN c.embedding <=> p_query_vector
               ELSE 1
             END
           )                                                    AS rnk
      FROM public.deal_document_chunks c
      JOIN public.deal_documents d ON d.id = c.document_id
     WHERE c.deal_id = p_deal_id
       AND (p_party IS NULL OR d.source_party = p_party)
     LIMIT 50
  ),
  keyword AS (
    SELECT c.id,
           ts_rank(c.content_fts, websearch_to_tsquery('english', p_query_text)) AS score,
           ROW_NUMBER() OVER (
             ORDER BY ts_rank(c.content_fts, websearch_to_tsquery('english', p_query_text)) DESC
           ) AS rnk
      FROM public.deal_document_chunks c
      JOIN public.deal_documents d ON d.id = c.document_id
     WHERE c.deal_id = p_deal_id
       AND (p_party IS NULL OR d.source_party = p_party)
       AND c.content_fts @@ websearch_to_tsquery('english', p_query_text)
     LIMIT 50
  ),
  fused AS (
    SELECT coalesce(s.id, k.id)                          AS chunk_id,
           coalesce(s.score, 0)::real                    AS semantic_score,
           coalesce(k.score, 0)::real                    AS keyword_score,
           (
             coalesce(1.0 / (60 + s.rnk), 0)
             + coalesce(1.0 / (60 + k.rnk), 0)
           )::real                                       AS fused_score
      FROM semantic s
      FULL OUTER JOIN keyword k ON s.id = k.id
  )
  SELECT f.chunk_id,
         c.document_id,
         d.filename,
         c.page_number,
         c.slide_number,
         c.sheet_name,
         c.cell_range,
         c.section_path,
         c.content,
         f.semantic_score,
         f.keyword_score,
         f.fused_score
    FROM fused f
    JOIN public.deal_document_chunks c ON c.id = f.chunk_id
    JOIN public.deal_documents       d ON d.id = c.document_id
   ORDER BY f.fused_score DESC
   LIMIT p_limit;
$$;

COMMENT ON FUNCTION public.search_deal_chunks IS
  'Hybrid (semantic + FTS) chunk search bounded to a single deal. RRF fusion. Pass query_vector NULL to fall back to keyword-only.';

-- ---------- Storage bucket ----------
-- Bucket creation is not always allowed via SQL; create via dashboard if this
-- INSERT errors. Bucket must be PRIVATE - documents may contain MNPI.
INSERT INTO storage.buckets (id, name, public)
VALUES ('deal-documents', 'deal-documents', false)
ON CONFLICT (id) DO NOTHING;
