export const PROCESS_TEMPLATES = [
  {
    id: 'invoice-approval',
    label: 'Invoice Approval',
    icon: '🧾',
    steps: [
      { name: 'Receive invoice', department: 'Finance', systems: ['Email'], workMinutes: 5 },
      { name: 'Check PO match', department: 'Finance', systems: ['ERP'], workMinutes: 10 },
      { name: 'Route for approval', department: 'Finance', systems: ['Email'], workMinutes: 5 },
      { name: 'Manager approves', department: 'Management', systems: ['Email'], workMinutes: 10, waitMinutes: 1440 },
      { name: 'Process payment', department: 'Finance', systems: ['ERP'], workMinutes: 10 },
    ],
  },
  {
    id: 'employee-onboarding',
    label: 'Employee Onboarding',
    icon: '👤',
    steps: [
      { name: 'Send offer letter', department: 'HR', systems: ['Email'], workMinutes: 15 },
      { name: 'Collect documentation', department: 'HR', systems: ['Email'], workMinutes: 30, waitMinutes: 2880 },
      { name: 'Create IT accounts', department: 'IT', systems: ['Active Directory'], workMinutes: 30, waitMinutes: 480 },
      { name: 'Assign equipment', department: 'IT', systems: [], workMinutes: 20 },
      { name: 'Run induction training', department: 'HR', systems: [], workMinutes: 120 },
      { name: 'Set up payroll', department: 'Finance', systems: ['HR System'], workMinutes: 20 },
    ],
  },
  {
    id: 'sales-quote',
    label: 'Sales Quote',
    icon: '💼',
    steps: [
      { name: 'Qualify opportunity', department: 'Sales', systems: ['CRM'], workMinutes: 30 },
      { name: 'Build quote', department: 'Sales', systems: ['CRM', 'Excel'], workMinutes: 60 },
      { name: 'Internal review', department: 'Management', systems: ['Email'], workMinutes: 20, waitMinutes: 240 },
      { name: 'Send to prospect', department: 'Sales', systems: ['Email'], workMinutes: 10 },
      { name: 'Follow up', department: 'Sales', systems: ['CRM', 'Email'], workMinutes: 20, waitMinutes: 2880 },
      { name: 'Process order', department: 'Operations', systems: ['ERP'], workMinutes: 30 },
    ],
  },
  {
    id: 'contract-review',
    label: 'Contract Review',
    icon: '📄',
    steps: [
      { name: 'Receive contract', department: 'Legal', systems: ['Email'], workMinutes: 5 },
      { name: 'Initial review', department: 'Legal', systems: [], workMinutes: 120 },
      { name: 'Raise redlines', department: 'Legal', systems: ['Word'], workMinutes: 60 },
      { name: 'Negotiate terms', department: 'Legal', systems: ['Email'], workMinutes: 30, waitMinutes: 2880 },
      { name: 'Final approval', department: 'Management', systems: ['Email'], workMinutes: 20, waitMinutes: 480 },
      { name: 'Execute and file', department: 'Legal', systems: ['DocuSign'], workMinutes: 15 },
    ],
  },
  {
    id: 'expense-claim',
    label: 'Expense Claim',
    icon: '💳',
    steps: [
      { name: 'Submit receipts', department: 'Employee', systems: ['Expense Tool', 'Email'], workMinutes: 15 },
      { name: 'Line manager review', department: 'Management', systems: ['Expense Tool'], workMinutes: 10, waitMinutes: 1440 },
      { name: 'Finance validation', department: 'Finance', systems: ['Expense Tool'], workMinutes: 10 },
      { name: 'Process payment', department: 'Finance', systems: ['ERP'], workMinutes: 10 },
    ],
  },
  {
    id: 'purchase-order',
    label: 'Purchase Order',
    icon: '🛒',
    steps: [
      { name: 'Raise purchase request', department: 'Requester', systems: ['ERP', 'Email'], workMinutes: 15 },
      { name: 'Budget check', department: 'Finance', systems: ['ERP'], workMinutes: 10 },
      { name: 'Approval', department: 'Management', systems: ['Email'], workMinutes: 10, waitMinutes: 480 },
      { name: 'Raise PO', department: 'Finance', systems: ['ERP'], workMinutes: 10 },
      { name: 'Send to supplier', department: 'Procurement', systems: ['Email'], workMinutes: 5 },
      { name: 'Goods receipt', department: 'Operations', systems: ['ERP'], workMinutes: 15 },
    ],
  },
  {
    id: 'client-onboarding',
    label: 'Client Onboarding',
    icon: '🤝',
    steps: [
      { name: 'KYC check', department: 'Compliance', systems: ['CRM'], workMinutes: 60, waitMinutes: 2880 },
      { name: 'Contract signed', department: 'Sales', systems: ['DocuSign'], workMinutes: 10, waitMinutes: 1440 },
      { name: 'Set up accounts', department: 'Operations', systems: ['CRM', 'ERP'], workMinutes: 30 },
      { name: 'Kick-off call', department: 'Client Success', systems: ['Zoom'], workMinutes: 60 },
      { name: 'Deliver welcome pack', department: 'Client Success', systems: ['Email'], workMinutes: 20 },
    ],
  },
  {
    id: 'it-access-request',
    label: 'IT Access Request',
    icon: '🔑',
    steps: [
      { name: 'Submit request', department: 'Employee', systems: ['IT Helpdesk'], workMinutes: 5 },
      { name: 'Manager approval', department: 'Management', systems: ['IT Helpdesk', 'Email'], workMinutes: 10, waitMinutes: 480 },
      { name: 'Security review', department: 'IT', systems: ['IT Helpdesk'], workMinutes: 15 },
      { name: 'Provision access', department: 'IT', systems: ['Active Directory'], workMinutes: 10 },
      { name: 'Confirm to user', department: 'IT', systems: ['IT Helpdesk', 'Email'], workMinutes: 5 },
    ],
  },
  {
    id: 'performance-review',
    label: 'Performance Review',
    icon: '⭐',
    steps: [
      { name: 'Self-assessment form', department: 'Employee', systems: ['HR System'], workMinutes: 60, waitMinutes: 2880 },
      { name: 'Manager review', department: 'Management', systems: ['HR System'], workMinutes: 45 },
      { name: 'Calibration meeting', department: 'HR', systems: [], workMinutes: 60 },
      { name: 'Review conversation', department: 'Management', systems: [], workMinutes: 60 },
      { name: 'Set objectives', department: 'HR', systems: ['HR System'], workMinutes: 20 },
    ],
  },
  {
    id: 'supplier-approval',
    label: 'Supplier Approval',
    icon: '🏭',
    steps: [
      { name: 'Submit supplier details', department: 'Procurement', systems: ['ERP', 'Email'], workMinutes: 20 },
      { name: 'Due diligence check', department: 'Compliance', systems: [], workMinutes: 60, waitMinutes: 2880 },
      { name: 'Financial review', department: 'Finance', systems: [], workMinutes: 30 },
      { name: 'Management approval', department: 'Management', systems: ['Email'], workMinutes: 10, waitMinutes: 480 },
      { name: 'Onboard in system', department: 'Procurement', systems: ['ERP'], workMinutes: 15 },
    ],
  },
  {
    id: 'monthly-close',
    label: 'Monthly Financial Close',
    icon: '📊',
    steps: [
      { name: 'Collate transactions', department: 'Finance', systems: ['ERP'], workMinutes: 120 },
      { name: 'Reconcile accounts', department: 'Finance', systems: ['ERP', 'Excel'], workMinutes: 180 },
      { name: 'Prepare management accounts', department: 'Finance', systems: ['Excel'], workMinutes: 120 },
      { name: 'Review and sign-off', department: 'Management', systems: ['Email'], workMinutes: 60, waitMinutes: 480 },
      { name: 'Distribute to stakeholders', department: 'Finance', systems: ['Email'], workMinutes: 20 },
    ],
  },
  {
    id: 'incident-response',
    label: 'Incident Response',
    icon: '🚨',
    steps: [
      { name: 'Detect and log incident', department: 'IT', systems: ['IT Helpdesk'], workMinutes: 10 },
      { name: 'Assess severity', department: 'IT', systems: [], workMinutes: 15 },
      { name: 'Notify stakeholders', department: 'IT', systems: ['Email', 'Slack'], workMinutes: 10 },
      { name: 'Investigate and resolve', department: 'IT', systems: [], workMinutes: 120 },
      { name: 'Post-incident review', department: 'IT', systems: [], workMinutes: 60 },
      { name: 'Document learnings', department: 'IT', systems: ['Confluence', 'Wiki'], workMinutes: 30 },
    ],
  },
];
